modLoader="javafml"
loaderVersion="[61,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="particle_graphics_library"
version="1.0.0"
displayName="PartiGLib"
#logoFile="examplemod.png"
authors="Fealtous"
displayTest="IGNORE_SERVER_VERSION"
description='''A library for creating entity-like objects for the purpose of drawing arbitrary shapes.'''
[[dependencies.particle_graphics_library]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.particle_graphics_library]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"

